[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "5pzbUo5NyQXYwW6kbA2Y2FwozaGGtjKixf8yzxFjkT5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/daniels7k/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
